branch-defaults:
  default:
    environment: fp-prod-env        # назва env, що створить eb create
global:
  application_name: fp-app
  default_platform: Docker          # каже EB використовувати Docker‑платформу
  region: eu-central-1              # ваш регіон
  profile: fp-deployer              # IAM‑профіль CLI
