branch-defaults:
  default:
    environment: fp-prod-env
  main:
    environment: null
global:
  application_name: fp-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: fp-deployer
  repository: null
  sc: git
  workspace_type: Application
